meta_product_name: "Business Bites"
meta_title: "Only one bite away from finding the perfect restaurant"
meta_description: "Waisting time to find a suitable restaurant is a thing of the past. Business Bites helps you to find amazing restaurants for your next corporate dinner!"
meta_image: "cibusinessbites.jpg"
